USE CTE_DB;
-- GET ALL TABLE ALONG WITH THEIR COLUMNS
SELECT UPPER(TABLE_NAME),': ',UPPER(GROUP_CONCAT(COLUMN_NAME ORDER BY ORDINAL_POSITION SEPARATOR ' ,')) AS COLS
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='CTE_DB'
GROUP BY UPPER(TABLE_NAME);

-- CUSTOMERS	: 	CUSTOMER_ID ,NAME ,EMAIL ,CREATED_AT
-- EMPLOYEES	: 	EMP_ID ,NAME ,MANAGER_ID
-- EVENTS		: 	EVENT_ID ,USER_ID ,EVENT_TIME ,EVENT_TYPE
-- HOLIDAYS		: 	HOLIDAY_DATE ,DESCRIPTION
-- METRICS		: 	ID ,ENTITY_ID ,TS ,VALUE ,X ,Y
-- ORDERS		: 	ORDER_ID ,CUSTOMER_ID ,ORDER_DATE ,AMOUNT
-- PRODUCTS		: 	PROD_ID ,SKU ,NAME ,UPDATED_AT
-- RESPONSES	: 	RESPONSE_ID ,TICKET_ID ,RESPONDER_ID ,RESPONDED_AT
-- SALES		: 	SALE_ID ,PRODUCT_ID ,STORE_ID ,SALE_DATE ,AMOUNT
-- SNAPSHOT_NEW	: 	ID ,COL1 ,COL2 ,UPDATED_AT
-- SNAPSHOT_OLD	: 	ID ,COL1 ,COL2 ,UPDATED_AT
-- TICKETS		: 	TICKET_ID ,CREATED_AT
-- USER_ACTIVITY	: 	ID ,USER_ID ,ACTIVITY_DATE
-- VISITS		: 	VISIT_ID ,PATIENT_ID ,VISIT_DATE

-- Q1. Find the top 3 customers by total annual spend for each year. Tables: orders(customer_id, order_date, amount)
WITH TOP3 AS
(
	SELECT C.CUSTOMER_ID,YEAR(O.ORDER_DATE) AS YEAR_OF_ORDER,SUM(O.AMOUNT) AS TOTAL_REV FROM CUSTOMERS C JOIN ORDERS O 
    ON C.CUSTOMER_ID=O.CUSTOMER_ID GROUP BY C.CUSTOMER_ID, YEAR(O.ORDER_DATE) ORDER BY SUM(O.AMOUNT) DESC LIMIT 3
)
SELECT * FROM TOP3;

-- Q2. Detect patients with gaps of more than 90 days between visits. Tables: visits(patient_id, visit_date)
WITH CTEX AS
(
SELECT *,LAG(VISIT_DATE) OVER(PARTITION BY PATIENT_ID ORDER BY VISIT_DATE) AS PREV_VISIT_DATE,
DATEDIFF(VISIT_DATE,LAG(VISIT_DATE) OVER(PARTITION BY PATIENT_ID ORDER BY VISIT_DATE)) AS DAYS_BTW_CONSECUTIVE_VISIT
 FROM VISITS
) SELECT * FROM CTEX WHERE DAYS_BTW_CONSECUTIVE_VISIT>90;

-- Q3. Return the median order amount per customer. Tables: orders(order_id, customer_id, amount)
SELECT AVG(AMOUNT) FROM
(
SELECT C.CUSTOMER_ID,C.NAME,O.ORDER_ID,O.ORDER_DATE,O.AMOUNT, 
ROW_NUMBER() OVER(ORDER BY O.AMOUNT) AS RN,
COUNT(*) OVER() AS TOT_CNT FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
) X WHERE 
X.RN IN 
( FLOOR((TOT_CNT+1)/2),FLOOR((TOT_CNT+2)/2));

-- Q4. Compute cumulative distinct product count over time. Tables: sales(product_id, sale_date)
WITH CTEY AS
(
SELECT P.PROD_ID,S.SALE_DATE,ROW_NUMBER() OVER(PARTITION BY P.PROD_ID ORDER BY S.SALE_DATE) AS RNK FROM PRODUCTS P JOIN SALES S
ON P.PROD_ID=S.PRODUCT_ID ORDER BY P.PROD_ID
),FIRST_OCCURANCE AS
(
SELECT SALE_DATE FROM CTEY WHERE RNK=1 ORDER BY SALE_DATE
),
PRODUCT_PER_DAY AS
(	
	SELECT SALE_DATE,COUNT(*) AS NEW_PROD FROM FIRST_OCCURANCE
    GROUP BY SALE_DATE ORDER BY SALE_DATE
) 
SELECT SALE_DATE,SUM(NEW_PROD) OVER(ORDER BY SALE_DATE) AS CUME_DISTINCT FROM PRODUCT_PER_DAY;

WITH FIRST_OCCURRENCE AS (
    SELECT 
        PRODUCT_ID,
        MIN(SALE_DATE) AS SALE_DATE
    FROM SALES
    GROUP BY PRODUCT_ID
),
PRODUCT_PER_DAY AS (
    SELECT 
        SALE_DATE,
        COUNT(*) AS NEW_PROD
    FROM FIRST_OCCURRENCE
    GROUP BY SALE_DATE
)
SELECT 
    SALE_DATE,
    SUM(NEW_PROD) OVER (ORDER BY SALE_DATE) AS CUME_DISTINCT
FROM PRODUCT_PER_DAY
ORDER BY SALE_DATE;

-- Q5. Find employees who indirectly report to  manager 14. Tables: employees(emp_id, manager_id)
SELECT * FROM EMPLOYEES;

WITH RECURSIVE EMP_CTE AS
(
	SELECT EMP_ID AS HEAD_EMP,
    EMP_ID,MANAGER_ID
    FROM EMPLOYEES
    UNION ALL
    SELECT EC.HEAD_EMP, E.EMP_ID,E.MANAGER_ID
    FROM EMP_CTE EC JOIN EMPLOYEES E
    ON EC.MANAGER_ID=E.EMP_ID
) SELECT HEAD_EMP AS MAIN_EMP_ID,EMP_ID AS LAST_INDIRECT_REPORT FROM EMP_CTE
 WHERE MANAGER_ID IS NULL ORDER BY HEAD_EMP;

-- Q6. Pivot monthly sales into columns. Tables: sales(store_id, sale_date, amount)
SELECT STORE_ID,UPPER(CONCAT(SUBSTR(MONTHNAME(SALE_DATE),1,3),'-',YEAR(SALE_DATE))) AS 'MON-YYYY',SUM(AMOUNT) FROM SALES WHERE STORE_ID=2
GROUP BY STORE_ID, UPPER(CONCAT(SUBSTR(MONTHNAME(SALE_DATE),1,3),'-',YEAR(SALE_DATE)));

-- LET SAY WE NEED PIVOTED RESULT FOR STORE 2 FOR JAN-2025,FEB-2025,MAR-2025, LET'S FIRST CREATE A CTE, SO THAT WE CAN USE IT FURTHER FOR EASE
WITH PIV_CTE AS
(
	SELECT STORE_ID,UPPER(CONCAT(SUBSTR(MONTHNAME(SALE_DATE),1,3),'-',YEAR(SALE_DATE))) AS SALEDATE,AMOUNT FROM SALES
)
SELECT STORE_ID,
		SUM(CASE WHEN SALEDATE='JAN-2025' THEN AMOUNT ELSE 0 END) AS 'JAN-2025',
        SUM(CASE WHEN SALEDATE='FEB-2025' THEN AMOUNT ELSE 0 END) AS 'FEB-2025',
        SUM(CASE WHEN SALEDATE='MAR-2025' THEN AMOUNT ELSE 0 END) AS 'MAR-2025'
FROM PIV_CTE
GROUP BY STORE_ID;

-- Q7. Identify customers with anomalous purchase amounts. Tables: orders(customer_id, amount) -- WILL USE IQR TO FIND OUTLIER,
-- X IS OUTLIER IF X< Q1-1.5*IQR OR X>Q3+1.5*IQR, Q1 IS 25 PERCENTILE, Q3 IS 75TH PERCENTILE AND IQR IS Q3-Q1
WITH CUME_CTE AS
(
SELECT AMOUNT, CUME_DIST() OVER(ORDER BY AMOUNT) AS CUME FROM ORDERS
), IQR AS
(
	 SELECT 
		MIN(CASE WHEN CUME=0.25 THEN AMOUNT END) AS Q1,  -- WHEN NEED TO GET 1 ROW, WE CAN USE MIN OR MAX TO GET THAT ROW
        MIN(CASE WHEN CUME=0.75 THEN AMOUNT END) AS Q3
	FROM CUME_CTE
), OUTLIER_AMOUNT AS
(
	SELECT Q1-1.5*(Q3-Q1) AS MIN_RANGE,
    Q3+1.5*(Q3-Q1) AS MAX_RANGE
    FROM IQR
) SELECT CUSTOMER_ID,ORDER_ID,AMOUNT AS OUTLIER_AMOUNT FROM ORDERS WHERE AMOUNT<(SELECT MIN_RANGE FROM OUTLIER_AMOUNT)
OR AMOUNT>(SELECT MIN_RANGE FROM OUTLIER_AMOUNT) ORDER BY AMOUNT;
    

-- Q8. Remove duplicate products keeping latest record. Tables: products(prod_id, sku, updated_at)
-- LET'S SEE THE TABLE FIRST
SELECT * FROM PRODUCTS;
-- FIND OUT IF THERE ARE MULTIPLE ROWS FOR SAME SKU AND PRODUCT_NAME
WITH ROW_CTE AS
(
SELECT *, ROW_NUMBER() OVER(PARTITION BY SKU,NAME ORDER BY UPDATED_AT DESC) AS RN FROM PRODUCTS
) 
SELECT * FROM ROW_CTE R1 WHERE R1.RN <> (SELECT MAX(R2.RN) FROM ROW_CTE R2 WHERE R1.PROD_ID=R2.PROD_ID);

-- Q9. Sessionize user events by inactivity >30 mins. Tables: events(user_id, event_time)
WITH TIME_CTE AS
(
SELECT *,TIMESTAMPDIFF(MINUTE,EVENT_TIME,LEAD(EVENT_TIME) OVER(PARTITION BY USER_ID ORDER BY EVENT_TIME)) AS NEXT_EVENT_DIFF_IN_MINS,
ROW_NUMBER() OVER(PARTITION BY USER_ID ORDER BY EVENT_TIME) AS RN FROM EVENTS
) 
SELECT *
 FROM TIME_CTE;
 
 WITH time_cte AS (
    SELECT 
        *,
        TIMESTAMPDIFF(
            MINUTE,
            LAG(event_time) OVER (PARTITION BY user_id ORDER BY event_time),
            event_time
        ) AS diff_mins
    FROM events
),

session_flag AS (
    SELECT *,
        CASE 
            WHEN diff_mins IS NULL OR diff_mins > 30 THEN 1
            ELSE 0
        END AS new_session
    FROM time_cte
),

sessionized AS (
    SELECT *,
        SUM(new_session) OVER (
            PARTITION BY user_id 
            ORDER BY event_time
        ) AS session_id
    FROM session_flag
)

SELECT *
FROM sessionized;

-- Q10. Calculate customer lifetime value (CLV). Tables: orders(customer_id, order_date, amount)
SELECT CUSTOMER_ID,MIN(ORDER_DATE) AS FIRST_ORDER_DATE, MAX(ORDER_DATE) AS LAST_ORDER_DATE,
SUM(AMOUNT) AS TOTAL_REV FROM ORDERS GROUP BY CUSTOMER_ID ORDER BY CUSTOMER_ID;

