USE CTE_DB;
-- GET ALL TABLE ALONG WITH THEIR COLUMNS
SELECT UPPER(TABLE_NAME),': ',UPPER(GROUP_CONCAT(COLUMN_NAME ORDER BY ORDINAL_POSITION SEPARATOR ' ,')) AS COLS
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='CTE_DB'
GROUP BY UPPER(TABLE_NAME);

-- CUSTOMERS	: 	CUSTOMER_ID ,NAME ,EMAIL ,CREATED_AT
-- EMPLOYEES	: 	EMP_ID ,NAME ,MANAGER_ID
-- EVENTS		: 	EVENT_ID ,USER_ID ,EVENT_TIME ,EVENT_TYPE
-- HOLIDAYS		: 	HOLIDAY_DATE ,DESCRIPTION
-- METRICS		: 	ID ,ENTITY_ID ,TS ,VALUE ,X ,Y
-- ORDERS		: 	ORDER_ID ,CUSTOMER_ID ,ORDER_DATE ,AMOUNT
-- PRODUCTS		: 	PROD_ID ,SKU ,NAME ,UPDATED_AT
-- RESPONSES	: 	RESPONSE_ID ,TICKET_ID ,RESPONDER_ID ,RESPONDED_AT
-- SALES		: 	SALE_ID ,PRODUCT_ID ,STORE_ID ,SALE_DATE ,AMOUNT
-- SNAPSHOT_NEW	: 	ID ,COL1 ,COL2 ,UPDATED_AT
-- SNAPSHOT_OLD	: 	ID ,COL1 ,COL2 ,UPDATED_AT
-- TICKETS		: 	TICKET_ID ,CREATED_AT
-- USER_ACTIVITY	: 	ID ,USER_ID ,ACTIVITY_DATE
-- VISITS		: 	VISIT_ID ,PATIENT_ID ,VISIT_DATE

-- Q11. Compute weighted moving average over time. Tables: metrics(entity_id, ts, value)
SELECT * FROM METRICS; -- X AND Y ARE THE WEIGHT
-- RUNNING WEIGHTED AVG
SELECT *, SUM(VALUE*X*Y) OVER(PARTITION BY ENTITY_ID ORDER BY TS) AS MOVING_WEIGHTED_AVG FROM METRICS;

-- Q12. Find longest consecutive activity streak per user. Tables: user_activity(user_id, activity_date)
SELECT *, row_number() over(partition by user_id order by activity_date) as rn FROM USER_ACTIVITY where user_id=30 ORDER BY USER_ID,ACTIVITY_DATE ;
SELECT *, LAG(ACTIVITY_DATE) OVER(PARTITION BY USER_ID ORDER BY ACTIVITY_DATE) AS PREV_ACTIVITY FROM USER_ACTIVITY;
WITH ACTIVITY_CTE AS
(
	SELECT *, LAG(ACTIVITY_DATE) OVER(PARTITION BY USER_ID ORDER BY ACTIVITY_DATE) AS PREV_ACTIVITY,
    DATEDIFF(ACTIVITY_DATE,LAG(ACTIVITY_DATE) OVER(PARTITION BY USER_ID ORDER BY ACTIVITY_DATE)) AS DIFF_BTW_SESSIONS
    FROM USER_ACTIVITY
), SESSION_CTE AS
(
	SELECT *,
    CASE WHEN DIFF_BTW_SESSIONS IS NULL OR DIFF_BTW_SESSIONS>1 THEN 1 ELSE 0 END AS NEW_SESSION
    FROM ACTIVITY_CTE
),USER_STREAK AS
(
	SELECT *, SUM(NEW_SESSION) OVER(PARTITION BY USER_ID ORDER BY ACTIVITY_DATE) AS SESSION_NUMBER
    FROM SESSION_CTE
)
 SELECT USER_ID,MIN(ACTIVITY_DATE) AS FIRST_DAY,MAX(ACTIVITY_DATE) AS LAST_DAY, SESSION_NUMBER,COUNT(*) AS DAYS_IN_STREAK FROM USER_STREAK
 GROUP BY USER_ID,SESSION_NUMBER ORDER BY COUNT(*) DESC;

-- Q13. Generate hierarchical JSON for org chart. Tables: employees(emp_id, manager_id)

-- Q14. Median time-to-first-response for tickets. Tables: tickets(ticket_id, created_at), responses(ticket_id, responded_at)
WITH FIRST_RESP_CTE AS
(
	SELECT TICKET_ID,CREATED_AT,RESPONSE_ID,RESPONDER_ID,RESPONDED_AT,TIME_DIFF FROM
	(
		SELECT T.TICKET_ID,T.CREATED_AT,R.RESPONSE_ID,R.RESPONDER_ID,R.RESPONDED_AT,
        TIMESTAMPDIFF(MINUTE,CREATED_AT,RESPONDED_AT) AS TIME_DIFF,
        ROW_NUMBER() OVER(PARTITION BY T.TICKET_ID ORDER BY R.RESPONDED_AT) AS RN
		FROM TICKETS T JOIN RESPONSES R ON T.TICKET_ID=R.TICKET_ID ORDER BY T.TICKET_ID,R.RESPONDED_AT
	) X WHERE X.RN=1
),MEDIAN_RESP_CTE AS
( 
	SELECT *, ROW_NUMBER() OVER(ORDER BY TIME_DIFF,TICKET_ID) AS IND,(SELECT COUNT(*) FROM FIRST_RESP_CTE) AS TOT_COUNT FROM FIRST_RESP_CTE
)
SELECT AVG(TIME_DIFF) AS MTTR_IN_MINS FROM MEDIAN_RESP_CTE
WHERE IND IN (FLOOR((TOT_COUNT/2)+1),FLOOR((TOT_COUNT/2)+2));

-- Q15. Detect changes between two snapshots. Tables: snapshot_old, snapshot_new
SELECT * FROM SNAPSHOT_OLD;
SELECT * FROM SNAPSHOT_NEW;
WITH MASTER_CTE AS
(
	SELECT O.ID AS OLD_ID,O.COL1 AS OLD_NAME,O.COL2 AS OLD_VAL,N.ID AS NEW_ID,N.COL1 AS NEW_NAME,N.COL2 AS NEW_VAL
    FROM SNAPSHOT_OLD O LEFT JOIN SNAPSHOT_NEW N
	ON O.ID=N.ID
	UNION ALL
	SELECT O.ID AS OLD_ID,O.COL1 AS OLD_NAME,O.COL2 AS OLD_VAL,N.ID AS NEW_ID,N.COL1 AS NEW_NAME,N.COL2 AS NEW_VAL
    FROM SNAPSHOT_OLD O RIGHT JOIN SNAPSHOT_NEW N
	ON O.ID=N.ID
),UPDATE_CTE AS
(
	SELECT *,
    CASE
		WHEN NEW_ID IS NULL THEN 'DELETED'
        WHEN OLD_ID IS NULL THEN 'NEW ROW INSERTED'
        WHEN OLD_VAL<>NEW_VAL THEN 'UPDATED'
        ELSE NULL
	END AS ROW_ACTIVITY FROM MASTER_CTE
)
SELECT * FROM UPDATE_CTE WHERE ROW_ACTIVITY IS NOT NULL;

-- Q16. Contribution of each product to monthly revenue growth. Tables: sales(product_id, sale_date, amount)
SELECT * FROM SALES;
WITH MASTER_CTE AS
(
	SELECT PRODUCT_ID,SUBSTR(MONTHNAME(SALE_DATE),1,3) AS MON,SUM(AMOUNT) AS REV,
    (SELECT SUM(AMOUNT) FROM SALES) AS TOT_AMOUNT FROM SALES
    GROUP BY PRODUCT_ID,SUBSTR(MONTHNAME(SALE_DATE),1,3)
)
SELECT *,(REV/TOT_AMOUNT)*100 AS PERCENTAGE_CONTRI FROM MASTER_CTE ORDER BY (REV/TOT_AMOUNT)*100;

-- Q17. Compute 3-month rolling correlation. Tables: metrics(entity_id, month, x, y)
SELECT * FROM METRICS;
WITH MONTH_CTE AS
(
	SELECT MON,X1,Y1,X1*Y1 AS XY,X1*X1 AS X1_SQ,Y1*Y1 AS Y1_SQ FROM
    (
		SELECT DATE_FORMAT(TS, '%Y-%m') AS MON,SUM(X) AS X1,SUM(Y) AS Y1
		FROM METRICS GROUP BY DATE_FORMAT(TS, '%Y-%m')
	) X
),
RUNNING_CTE AS
(
	SELECT MON, 
    SUM(X1) OVER(ORDER BY MON ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS SUM_X,
    SUM(Y1) OVER(ORDER BY MON ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS SUM_Y,
    SUM(XY) OVER(ORDER BY MON ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS SUM_XY,
    SUM(X1_SQ) OVER(ORDER BY MON ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS SUM_X1_2,
    SUM(Y1_SQ) OVER(ORDER BY MON ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS SUM_Y1_2,
    COUNT(*) OVER(ORDER BY MON ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS CNT
    FROM MONTH_CTE
)
SELECT MON,(SUM_XY-(SUM_X*SUM_Y)/CNT)/SQRT((SUM_X1_2-(SUM_X*SUM_X)/CNT)*(SUM_Y1_2-(SUM_Y*SUM_Y)/CNT)) AS CR
 FROM RUNNING_CTE;


-- Q18. Rank products by recency-weighted sales. Tables: sales(product_id, sale_date, amount)
SELECT * FROM SALES ORDER BY SALE_DATE; -- > WE WILL CALCULATE WEIGHT BASED ON FORMULA 1/(DAYS_SINCE_SALE+1)

WITH CTX AS
(
SELECT *, 1/(DATEDIFF('2025-12-01',SALE_DATE)+1) AS WEIGHT FROM SALES ORDER BY SALE_DATE DESC
)
SELECT *,AMOUNT*WEIGHT AS WEIGHTED_SALES FROM CTX
;
-- Q19. Find orphaned rows violating FK. Tables: orders(customer_id), customers(customer_id)
SELECT * FROM ORDERS WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM CUSTOMERS);

-- Q20. Generate business-day calendar excluding holidays. Tables: holidays(holiday_date)
SELECT * FROM HOLIDAYS;
WITH RECURSIVE DATES AS
(
	SELECT DATE('2024-01-01') AS DT
    UNION ALL 
    SELECT DT+ INTERVAL 1 DAY
    FROM DATES WHERE DT<'2025-12-31'
)
SELECT *,DAYNAME(DT),
CASE 
	WHEN UPPER(DAYNAME(DT)) IN ('SUNDAY','SATURDAY') THEN 'WEEKEND'
    WHEN DT IN (SELECT HOLIDAY_DATE FROM HOLIDAYS) THEN (SELECT MAX(DESCRIPTION) FROM HOLIDAYS WHERE HOLIDAY_DATE=DT)
    ELSE 'WORKING DAYS'
    END AS CALENDER
FROM DATES;
