USE CUSTOMER_DATABASE;

-- **************QUESTIONS**************** Known customers.customer_id=orders.customer_id

-- Q1: Show customer_name and product_name. 
SELECT C.CUSTOMER_NAME,O.PRODUCT_NAME FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID; -- It will give the names of those customers who have placed some order as we are using inner join

-- Q2: Show customer_name and amount.
SELECT C.CUSTOMER_NAME,O.PRODUCT_NAME,O.AMOUNT FROM CUSTOMERS C LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID ORDER BY C.CUSTOMER_NAME; -- It will give the name of all the customers even when they haven't placed any order coz of LEFT JOIN

-- Q3: Show city and product_name.
SELECT C.CITY,O.PRODUCT_NAME FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID ORDER BY C.CITY;

-- Q4: Show customers who placed orders.
SELECT C.CUSTOMER_NAME FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID; -- it will only give those names who have placed orders

-- Q5: Show all customers with orders.
SELECT C.CUSTOMER_NAME FROM CUSTOMERS C LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- Q6: Show customers without orders.
SELECT C.CUSTOMER_NAME,O.CUSTOMER_ID FROM CUSTOMERS C LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE O.CUSTOMER_ID IS NULL; 
-- the customers in orders where customer_id is null is coz of those customer ids are not in orders table

-- Q7: Show Delhi customers with orders.
SELECT C.CUSTOMER_NAME, C.CITY, O.ORDER_ID FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE C.CITY='Delhi';

-- Q8: Show Mumbai customers and products bought.
SELECT C.CUSTOMER_NAME, C.CITY, O.PRODUCT_NAME FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE C.CITY='Mumbai';

-- Q9: Show customer total spending.
SELECT C.CUSTOMER_NAME, SUM(O.AMOUNT) FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID 
GROUP BY C.CUSTOMER_ID;

-- Q10: Show highest spender.
SELECT C.CUSTOMER_NAME, SUM(O.AMOUNT) FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY SUM(AMOUNT) DESC LIMIT 1;

-- Q11: Show lowest spender.
SELECT C.CUSTOMER_NAME, SUM(O.AMOUNT) FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY SUM(AMOUNT) ASC LIMIT 1;

-- Q12: Show city-wise revenue.
SELECT C.CITY, SUM(O.AMOUNT) FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY;

-- Q13: Show customers who bought laptops.
SELECT C.CUSTOMER_NAME, O.PRODUCT_NAME FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE O.PRODUCT_NAME='Laptop';

-- Q14: Show customers with multiple orders.
SELECT C.CUSTOMER_NAME, COUNT(O.ORDER_ID) FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
HAVING COUNT(O.ORDER_ID)>1;

-- Q15: Show top spender city-wise.
-- TO GET CITY-WISE MAX SPEND
SELECT MAX(O.AMOUNT) AS BIG_SPEND ,C.CITY FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY ORDER BY MAX(O.AMOUNT) DESC; 
--
-- First we are creating select of select for cutomers join orders to treat them in a single table rather than joined
-- Then we are joining the max_amount per city 
--
SELECT C1.CUSTOMER_NAME, C1.AMOUNT, C1.CITY FROM
(
SELECT C.CUSTOMER_NAME,O.AMOUNT,C.CITY FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
) C1
JOIN
(
SELECT MAX(O.AMOUNT) AS BIG_SPEND ,C.CITY FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY ORDER BY MAX(O.AMOUNT) DESC 
) T1
ON 
C1.CITY=T1.CITY AND
C1.AMOUNT=T1.BIG_SPEND
;

-- Q16: Show latest order per customer.
SELECT C1.CUSTOMER_NAME, C1.ORDER_ID,C1.PRODUCT_NAME,C1.ORDER_DATE FROM
(
SELECT C.CUSTOMER_NAME,O.ORDER_ID,O.PRODUCT_NAME,O.ORDER_DATE FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
) C1
JOIN
(
	SELECT C.CUSTOMER_NAME, MAX(O.ORDER_DATE) AS LATEST_DATE_ORDER FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
    GROUP BY C.CUSTOMER_NAME
) C2
ON C1.ORDER_DATE=C2.LATEST_DATE_ORDER;
    
-- Q17: Show customers whose spending > city average.
SELECT C1.CUSTOMER_NAME, C1.AMOUNT, C1.CITY FROM
(
SELECT C.CUSTOMER_NAME,O.AMOUNT,C.CITY FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
) C1
JOIN
(
SELECT AVG(O.AMOUNT) AS AVG_SPEND_PER_CITY ,C.CITY FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY
) T1
ON 
C1.CITY=T1.CITY AND
C1.AMOUNT>T1.AVG_SPEND_PER_CITY
;

-- Q18: Show customers buying multiple products.
SELECT C.CUSTOMER_NAME,COUNT(ORDER_ID) AS ORDER_COUNT FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME 
HAVING COUNT(ORDER_ID)>1;

-- Q19: Show customers whose first order was laptop.
-- We need to check what is the FIRST DATE OF ORDER for each customer
SELECT C.CUSTOMER_ID,MIN(O.ORDER_DATE) AS FIRST_ORDER_DATE FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID GROUP BY C.CUSTOMER_ID; -- Now we will write a query with join on this on which we will match the order date from both the tables

SELECT C1.CUSTOMER_ID,C1.CUSTOMER_NAME,C1.PRODUCT_NAME,C1.ORDER_DATE,C2.FIRST_ORDER_DATE FROM 
(
	SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,O.PRODUCT_NAME,O.ORDER_DATE FROM
    CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
) C1
JOIN
(
	SELECT C.CUSTOMER_ID,MIN(O.ORDER_DATE) AS FIRST_ORDER_DATE FROM CUSTOMERS C JOIN ORDERS O
	ON C.CUSTOMER_ID=O.CUSTOMER_ID GROUP BY C.CUSTOMER_ID
) C2
ON C1.CUSTOMER_ID=C2.CUSTOMER_ID AND
C1.ORDER_DATE=C2.FIRST_ORDER_DATE
;
-- Q20: Show customers contributing top revenue
-- > We need to sum up the total amount by each customer and then need to return the top contributer from it
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(O.AMOUNT)  FROM
CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY SUM(O.AMOUNT) DESC LIMIT 1;
