-- Q1. Assign a unique sequential number to each order in the dataset.

-- Q2. For each customer, assign a sequence number to their orders based on order date.

-- Q3. Display orders such that the most recent order of each customer appears first with a sequence number.

-- Q4. Rank all orders based on amount, ensuring that ties result in gaps in ranking.

-- Q5. Rank orders for each customer based on amount without skipping rank numbers for ties.

-- Q6. Identify the top 3 highest value orders in the entire dataset.

-- Q7. Identify the top 3 highest value orders for each customer.

-- Q8. Detect duplicate records in the orders table and assign a sequence to each duplicate group.

-- Q9. Assign a sequence to orders sorted by date and identify the exact position of each order in timeline.

-- Q10. For each order, display the amount of the immediately previous order in the dataset.

-- Q11. For each customer, show the amount of their previous order.

-- Q12. For each order, display the amount of the next order placed by the same customer.

-- Q13. Calculate the difference between the current order amount and the previous order amount for each customer.

-- Q14. Identify the first order placed by each customer.

-- Q15. Identify the most recent (last) order placed by each customer.

-- Q16. Calculate a running total of order amounts across the entire dataset ordered by date.

-- Q17. Calculate a running total of order amounts separately for each customer.

-- Q18. For each order, calculate the average of the current and previous two orders.

-- Q19. For each row, count how many orders have occurred up to that point in time.

-- Q20. Calculate cumulative revenue generated by each customer over time.

-- Q21. Divide all orders into 4 equal groups based on their order amounts.

-- Q22. Divide customers into 4 groups based on their total spending.

-- Q23. For each order, calculate its relative ranking as a percentage among all orders.

-- Q24. For each order, determine the proportion of orders that have an amount less than or equal to it.

-- Q25. Compare the relative ranking and cumulative distribution of order amounts for each row.

-- Q26. Identify orders where the current order amount is greater than the previous order amount for the same customer.

-- Q27. Calculate the difference in days between consecutive orders for each customer.

-- Q28. Determine whether each customer's order trend is increasing or decreasing compared to their previous order.

-- Q29. Identify the top 2 highest value orders for each customer.

-- Q30. For each customer, display both the running total of spending and their rank based on order amount within the same result.