USE DAY4;
SHOW TABLES;

SELECT TABLE_NAME, GROUP_CONCAT(COLUMN_NAME ORDER BY ORDINAL_POSITION SEPARATOR ' ,') AS COLUMNS FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='DAY4' GROUP BY TABLE_SCHEMA,TABLE_NAME; -- Get the name of table and it's columns 1 by 1

-- customers	CUSTOMER_ID ,CUSTOMER_NAME ,CITY ,DOB
-- order_items	ORDER_ID ,PRODUCT_ID ,QUANTITY
-- orders	ORDER_ID ,CUSTOMER_ID ,ORDER_DATE
-- payments	PAYMENT_ID ,ORDER_ID ,PAYMENT_DATE ,PAYMENT_AMOUNT ,STATUS
-- products	PRODUCT_ID ,PRODUCT_NAME ,CATEGORY ,PRICE

-- Q1. Assign a unique sequential number to each order in the dataset.
SELECT *, ROW_NUMBER() OVER(ORDER BY ORDER_ID) AS RN FROM ORDERS;

-- Q2. For each customer, assign a sequence number to their orders based on order date.
SELECT C.*,O.ORDER_ID,O.ORDER_DATE, ROW_NUMBER() OVER(PARTITION BY C.CUSTOMER_ID ORDER BY ORDER_DATE) AS RN FROM
CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- Q3. Display orders such that the most recent order of each customer appears first with a sequence number.
SELECT C.*,O.ORDER_ID,O.ORDER_DATE, ROW_NUMBER() OVER(PARTITION BY C.CUSTOMER_ID ORDER BY ORDER_DATE DESC) AS RN FROM
CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- Q4. Rank all orders based on amount, ensuring that ties result in gaps in ranking.
SELECT O.ORDER_ID,P.PAYMENT_ID,P.PAYMENT_AMOUNT, RANK() OVER(ORDER BY P.PAYMENT_AMOUNT) AS PAYMENT_RANK
FROM ORDERS O JOIN PAYMENTS P ON
O.ORDER_ID=P.ORDER_ID;

-- Q5. Rank orders for each customer based on amount without skipping rank numbers for ties.
SELECT O.CUSTOMER_ID,O.ORDER_ID,P.PAYMENT_AMOUNT, RANK() OVER(PARTITION BY O.CUSTOMER_ID ORDER BY P.PAYMENT_AMOUNT) AS PR
FROM ORDERS O JOIN PAYMENTS P ON
O.ORDER_ID=P.ORDER_ID;

-- Q6. Identify the top 3 highest value orders in the entire dataset.
SELECT ORDER_ID, PAYMENT_AMOUNT
FROM
(
	SELECT ORDER_ID, PAYMENT_AMOUNT, ROW_NUMBER() OVER(ORDER BY PAYMENT_AMOUNT) AS RN
    FROM PAYMENTS
) X WHERE X.RN<=3;

-- Q7. Identify the top 3 highest value orders for each customer.
SELECT CUSTOMER_ID, PAYMENT_ID,PAYMENT_AMOUNT
FROM
(
	SELECT O.CUSTOMER_ID, P.PAYMENT_ID,P.PAYMENT_AMOUNT, ROW_NUMBER() OVER(PARTITION BY O.CUSTOMER_ID ORDER BY P.PAYMENT_AMOUNT DESC) AS RNK
    FROM ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID
) X WHERE X.RNK<=3;

-- Q8. Detect duplicate records in the orders table and assign a sequence to each duplicate group.
SELECT * FROM
(
SELECT *, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID, ORDER_DATE) AS RNK FROM ORDERS
) X WHERE X.RNK>1;

-- Q9. Assign a sequence to orders sorted by date and identify the exact position of each order in timeline.
SELECT *,ROW_NUMBER() OVER(ORDER BY ORDER_DATE) AS ROW_INDEX FROM ORDERS;

-- Q10. For each order, display the amount of the immediately previous order in the dataset.
SELECT O.ORDER_ID,O.ORDER_DATE AS TODAYS_DATE,P.PAYMENT_AMOUNT AS CURRENT_AMOUNT, LAG(P.PAYMENT_AMOUNT) OVER(ORDER BY O.ORDER_DATE) AS PREV_ORDER_AMOUNT
FROM ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID;

-- Q11. For each customer, show the amount of their previous order.
SELECT O.CUSTOMER_ID,O.ORDER_ID,O.ORDER_DATE AS TODAYS_DATE,P.PAYMENT_AMOUNT AS CURRENT_AMOUNT, LAG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) AS PREV_ORDER_AMOUNT
FROM ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID;

-- Q12. For each order, display the amount of the next order placed by the same customer.
SELECT O.CUSTOMER_ID,O.ORDER_ID,O.ORDER_DATE AS TODAYS_DATE,P.PAYMENT_AMOUNT AS CURRENT_AMOUNT, 
LEAD(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) AS NEXT_ORDER_AMOUNT
FROM ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID;

-- Q13. Calculate the difference between the current order amount and the previous order amount for each customer.
SELECT O.CUSTOMER_ID,O.ORDER_ID,O.ORDER_DATE AS TODAYS_DATE,P.PAYMENT_AMOUNT AS CURRENT_AMOUNT, 
P.PAYMENT_AMOUNT-LAG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) AS CURRENT_TO_PREV_ORDER_AMOUNT_DIFF
FROM ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID;

-- Q14. Identify the first order placed by each customer.
SELECT CUSTOMER_ID,ORDER_ID,ORDER_DATE FROM
(
SELECT CUSTOMER_ID,ORDER_ID,ORDER_DATE,ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS RNK FROM ORDERS
) X WHERE X.RNK=1;

-- Q15. Identify the most recent (last) order placed by each customer.
SELECT CUSTOMER_ID,ORDER_ID,ORDER_DATE FROM
(
SELECT CUSTOMER_ID,ORDER_ID,ORDER_DATE,ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE DESC) AS RNK FROM ORDERS
) X WHERE X.RNK=1;

-- Q16. Calculate a running total of order amounts across the entire dataset ordered by date.
SELECT O.*,P.*, SUM(P.PAYMENT_AMOUNT) OVER(ORDER BY ORDER_DATE) AS RUNNING_TOTAL FROM 
ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID;
 -- > This Query will merge the amount per order id, foe exp- for order id 12- running sum is sum of order id 89, 12, 12, 12 even when the order status is failed or pending
 
 -- Best answer
SELECT O.*,P.*, SUM(P.PAYMENT_AMOUNT) OVER(ORDER BY ORDER_DATE) AS RUNNING_TOTAL FROM 
ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID WHERE P.STATUS='SUCCESS';

-- LET'S SAY WE NEED TO CALCULATE RUNNING TOTAL FOR ALL STATUS, WE WILL FIRST ASSIGN A ROW_NUMBER FOR EACH ROW AS PER ORDER_DATE AND THEN USE IT TO SUM OVER ROWNUMBER
SELECT *, SUM(PAYMENT_AMOUNT) OVER(ORDER BY RN) AS RUNNING_TOTAL
FROM
(
	SELECT O.ORDER_ID,P.PAYMENT_ID,P.PAYMENT_AMOUNT,P.STATUS, ROW_NUMBER() OVER(ORDER BY ORDER_DATE) AS RN FROM 
	ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID
) X;

-- Q17. Calculate a running total of order amounts separately for each customer.
SELECT O.ORDER_ID,O.CUSTOMER_ID,O.ORDER_DATE,P.PAYMENT_ID,P.STATUS,P.PAYMENT_AMOUNT,
SUM(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY P.PAYMENT_AMOUNT) AS RUNNING_TOTAL
FROM ORDERS O JOIN PAYMENTS P
ON O.ORDER_ID=P.PAYMENT_ID;

-- Q18. For each order, calculate the average of the current and previous two orders.
SELECT O.ORDER_ID,O.CUSTOMER_ID,O.ORDER_DATE,P.PAYMENT_ID,P.STATUS,P.PAYMENT_AMOUNT,
AVG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY P.PAYMENT_AMOUNT ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS RUNNING_AVG_PAST2
FROM ORDERS O JOIN PAYMENTS P
ON O.ORDER_ID=P.PAYMENT_ID;

-- Q19. For each row, count how many orders have occurred up to that point in time.
SELECT *, COUNT(*) OVER(ORDER BY ORDER_DATE,ORDER_ID) AS RUNNING_COUNT FROM ORDERS;

-- Q20. Calculate cumulative revenue generated by each customer over time.
SELECT O.ORDER_ID,O.CUSTOMER_ID,O.ORDER_DATE,P.PAYMENT_ID,P.STATUS,P.PAYMENT_AMOUNT,
SUM(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) AS CUMM_TOTAL
FROM ORDERS O JOIN PAYMENTS P
ON O.ORDER_ID=P.PAYMENT_ID;


-- FOR THE QUESTIONS BELOW WE WILL TAKE ONLY PAYMENT STATUS= SUCCESS IN CONSIDERATION
-- Q21. Divide all orders into 4 equal groups based on their order amounts.
SELECT O.ORDER_ID, P.PAYMENT_AMOUNT, NTILE(4) OVER(ORDER BY P.PAYMENT_AMOUNT) AS AMOUNT_BUCKET FROM
ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID WHERE P.STATUS='SUCCESS';

-- Q22. Divide customers into 4 groups based on their total spending.
SELECT *,NTILE(4) OVER(ORDER BY TOTAL_SPEND) AS CUTOMER_BUCKET_BY_TOTAL_SPEND FROM
(
SELECT O.CUSTOMER_ID,SUM(P.PAYMENT_AMOUNT) AS TOTAL_SPEND FROM ORDERS O JOIN PAYMENTS P
ON O.ORDER_ID=P.ORDER_ID WHERE P.STATUS='SUCCESS' GROUP BY O.CUSTOMER_ID ORDER BY O.CUSTOMER_ID
) X;

-- Q23. For each order, calculate its relative ranking as a percentage among all orders.
SELECT O.*,P.PAYMENT_AMOUNT,PERCENT_RANK() OVER(ORDER BY P.PAYMENT_AMOUNT) AS PERC_RANK
FROM ORDERS O JOIN PAYMENTS P
ON O.ORDER_ID=P.ORDER_ID WHERE P.STATUS='SUCCESS';

-- Q24. For each order, determine the proportion of orders that have an amount less than or equal to it.
SELECT O.*,P.PAYMENT_AMOUNT,CUME_DIST() OVER(ORDER BY O.ORDER_DATE) AS DISTRIBUTION
FROM ORDERS O JOIN PAYMENTS P
ON O.ORDER_ID=P.ORDER_ID WHERE P.STATUS='SUCCESS';

-- Q25. Compare the relative ranking and cumulative distribution of order amounts for each row.
SELECT O.*,P.PAYMENT_AMOUNT,PERCENT_RANK() OVER(ORDER BY O.ORDER_DATE) AS PERC_RANK,
CUME_DIST() OVER(ORDER BY O.ORDER_DATE) AS DISTRIBUTION
FROM ORDERS O JOIN PAYMENTS P
ON O.ORDER_ID=P.ORDER_ID WHERE P.STATUS='SUCCESS';

-- Q26. Identify orders where the current order amount is greater than the previous order amount for the same customer.
SELECT O.ORDER_ID,O.CUSTOMER_ID,P.PAYMENT_AMOUNT AS CURR_AMOUNT,
CASE
	WHEN P.PAYMENT_AMOUNT>LAG(P.PAYMENT_AMOUNT) OVER(ORDER BY O.ORDER_DATE) THEN 'GREATER'
    WHEN P.PAYMENT_AMOUNT=LAG(P.PAYMENT_AMOUNT) OVER(ORDER BY O.ORDER_DATE) THEN 'EQUAL'
    WHEN P.PAYMENT_AMOUNT<LAG(P.PAYMENT_AMOUNT) OVER(ORDER BY O.ORDER_DATE) THEN 'LOWER'
    ELSE NULL
END AS COMP_BTW_CURR_AND_PREV_AMOUNT
FROM ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID
WHERE P.STATUS='SUCCESS';

-- Q27. Calculate the difference in days between consecutive orders for each customer.
SELECT ORDER_ID,CUSTOMER_ID,ORDER_DATE AS CURR_DATE, 
DATEDIFF(ORDER_DATE,LAG(ORDER_DATE) OVER(PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE)) AS DIFF_BTW_CURR_AND_PERV_ORDER_DATE
FROM ORDERS;

-- Q28. Determine whether each customer's order trend is increasing or decreasing compared to their previous order.
SELECT O.ORDER_ID,O.CUSTOMER_ID,P.PAYMENT_AMOUNT AS CURR_AMOUNT,
CASE
	WHEN P.PAYMENT_AMOUNT>LAG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) THEN 'GREATER'
    WHEN P.PAYMENT_AMOUNT=LAG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) THEN 'EQUAL'
    WHEN P.PAYMENT_AMOUNT<LAG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) THEN 'LOWER'
    ELSE NULL
END AS COMP_BTW_CURR_AND_PREV_AMOUNT_PER_CUST
FROM ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID
WHERE P.STATUS='SUCCESS'
ORDER BY
CASE
	WHEN P.PAYMENT_AMOUNT>LAG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) THEN 1
    WHEN P.PAYMENT_AMOUNT=LAG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) THEN 2
    WHEN P.PAYMENT_AMOUNT<LAG(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) THEN 3
    ELSE 4
END;

-- Q29. Identify the top 2 highest value orders for each customer.
SELECT * FROM
(
SELECT O.ORDER_ID,O.CUSTOMER_ID,P.PAYMENT_AMOUNT,ROW_NUMBER() OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) AS RN
FROM ORDERS O JOIN PAYMENTS P ON O.ORDER_ID=P.ORDER_ID
WHERE P.STATUS='SUCCESS'
) X WHERE X.RN<3;

-- Q30. For each customer, display both the running total of spending and their rank based on order amount within the same result.
SELECT O.ORDER_ID,O.CUSTOMER_ID,O.ORDER_DATE,P.PAYMENT_ID,P.STATUS,P.PAYMENT_AMOUNT,
SUM(P.PAYMENT_AMOUNT) OVER(PARTITION BY O.CUSTOMER_ID ORDER BY O.ORDER_DATE) AS RUNNING_TOTAL,
RANK() OVER(PARTITION BY O.CUSTOMER_ID ORDER BY P.PAYMENT_AMOUNT) AS RANK_OF_AMT_WITHIN_CUST
FROM ORDERS O JOIN PAYMENTS P
ON O.ORDER_ID=P.PAYMENT_ID;