USE DAY2;

-- first let's have the column name from each of the table
SELECT GROUP_CONCAT(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='CUSTOMERS' AND TABLE_SCHEMA='DAY2'; -- city,customer_id,customer_name,dob,membership_type,signup_date

SELECT GROUP_CONCAT(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='ORDERS' AND TABLE_SCHEMA='DAY2'; -- amount,customer_id,delivery_date,order_date,order_id,payment_mode,status


-- CASE STATEMENT QUESTIONS
-- 1. Categorize amount. -- AMOUNT >50000 HIGH_VAL_ORDER ELSE LOW_VAL_ORDER
SELECT *,
	CASE
		WHEN AMOUNT>10000 THEN 'HIGH_VAL_ORDER'
        ELSE 'LOW_VAL_ORDER'
	END AS ORDER_CATEGORY
FROM ORDERS;
	
-- 2. Categorize membership.
SELECT CUSTOMER_ID,SUM(AMOUNT),
	CASE
		WHEN SUM(AMOUNT)>50000 THEN 'PREMIUM'
        ELSE 'REGULAR'
	END AS CUSTOMER_CATEGORY
FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY SUM(AMOUNT) DESC;

-- JUST TO VERIFY
SELECT SUM(AMOUNT) FROM ORDERS WHERE CUSTOMER_ID=42;

-- 3. Convert order status.
SELECT ORDER_ID,AMOUNT,ORDER_DATE,
CASE
	WHEN UPPER(STATUS)='COMPLETED' THEN 'C'
    WHEN UPPER(STATUS)='PENDING' THEN 'P'
    ELSE 'X'
END AS ORDER_STATUS
FROM ORDERS;

-- 4. Classify payment mode.
SELECT DISTINCT(PAYMENT_MODE) FROM ORDERS; -- GET ALL PAYMENT MODE
-- CLASSIFY UPI,CARD, AND NETBANKING AS DIGITAL, AND CASH AS OFFLINE
SELECT *,
CASE
	WHEN UPPER(PAYMENT_MODE) IN ('UPI','CARD','NETBANKING') THEN 'DIGITAL'
    ELSE 'OFFLINE'
END AS PAYMENT_TYPE
FROM ORDERS;

-- 5. Classify city.
-- GET UNIQUE CITIES FROM CUSTOMERS
SELECT DISTINCT(CITY) FROM CUSTOMERS;
SELECT CUSTOMER_NAME,
    CITY,
    CASE 
        WHEN CITY = 'Delhi' THEN 'North'
        WHEN CITY = 'Kolkata' THEN 'East'
        WHEN CITY IN ('Hyderabad', 'Chennai', 'Bangalore') THEN 'South'
        WHEN CITY IN ('Mumbai', 'Pune') THEN 'West'
        ELSE 'Unknown'
    END AS REGION
FROM CUSTOMERS;

-- 6. Create spending bands.
SELECT CUSTOMER_ID, SUM(AMOUNT),
CASE
	WHEN SUM(AMOUNT)>50000 THEN 'HIGH_SPEND'
    WHEN SUM(AMOUNT) BETWEEN 30000 AND 50000 THEN 'MID_SPEND'
    ELSE 'LOW_SPEND'
END AS SPEND_CATEGORY
FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY SUM(AMOUNT) DESC;

-- 7. Classify customers by signup year. -LET'S SAY THE CUSTOMER AFTER '2024 SEPTEMBER 01 WILL BE TREATED AS NEW
SELECT CUSTOMER_ID, CUSTOMER_NAME,
CASE 
	WHEN SIGNUP_DATE>'2024-09-01' THEN 'NEW USER'
    ELSE 'OLD USER'
END AS CUSTOMER_CATEGORY
FROM CUSTOMERS;

-- 8. Categorize delivery speed.
SELECT ORDER_ID,DELIVERY_DATE,ORDER_DATE,
CASE
	WHEN DATEDIFF(DELIVERY_DATE,ORDER_DATE)>=7 THEN 'LOW'
    WHEN DATEDIFF(DELIVERY_DATE,ORDER_DATE) BETWEEN 3 AND 6 THEN 'MEDIUM'
    ELSE 'HIGH'
END AS DELIVERY_SPEED
FROM ORDERS;

-- 9. Sort customers by membership priority.
-- > LET'S GET DISTINCT MEMBERSHIP TYPE FIRST 
SELECT DISTINCT(MEMBERSHIP_TYPE) FROM CUSTOMERS;
SELECT * FROM CUSTOMERS
ORDER BY 
CASE MEMBERSHIP_TYPE
	WHEN 'Gold' THEN 1
    WHEN 'Silver' THEN 2
    ELSE 3
    END;
    
-- 10. Sort orders by status.
SELECT ORDER_ID,STATUS FROM ORDERS
ORDER BY
	CASE UPPER(STATUS)
		WHEN 'COMPLETED' THEN 1
        WHEN 'PENDING' THEN 2
        ELSE 3
	END;
    
-- 11. Calculate completed sales.
SELECT 
	SUM(
		CASE UPPER(STATUS)
			WHEN 'COMPLETED' THEN AMOUNT
            ELSE 0
		END
    ) AS COMPLETED_SALES_AMOUNT
FROM ORDERS;

-- 12. Count pending orders.
SELECT 
	SUM(
		CASE UPPER(STATUS)
			WHEN 'PENDING' THEN 1
            ELSE 0
		END
    ) AS COUNT_OF_PENDING_ORDER
FROM ORDERS;
-- 13. Count premium customers city-wise.
SELECT CITY,
SUM(
	CASE UPPER(MEMBERSHIP_TYPE)
    WHEN 'GOLD' THEN 1
    ELSE 0
    END
) AS GOLD_MEMBER_COUNT
FROM CUSTOMERS
GROUP BY CITY;

-- 14. Categorize festival season.
SELECT ORDER_ID, ORDER_DATE,
CASE
	WHEN MONTH(ORDER_DATE) BETWEEN 10 AND 12 THEN 'YES'
    ELSE 'NO'
END AS FESTIVAL_SEASON
FROM ORDERS;

-- 15. Categorize weekend vs weekday.
SELECT ORDER_ID,ORDER_DATE,
CASE
	WHEN UPPER(DAYNAME(ORDER_DATE)) IN ('SUNDAY','SATURDAY') THEN 'WEEKEND'
    ELSE 'WEEKDAYS'
END AS DAY_OF_WEEK
FROM ORDERS;
-- 16. Nested CASE for VIP. We will identify those customers as VIP whose total spend is greater than 50k and membership type is gold
SELECT C.CUSTOMER_ID,SUM(O.AMOUNT) AS AMOUNT_SPEND,
CASE C.MEMBERSHIP_TYPE
	WHEN 'GOLD' THEN
		CASE
			WHEN SUM(O.AMOUNT)>50000 THEN 'VIP'
            ELSE 'REGULAR'
            END
	ELSE 'REGULAR'
END AS CUSTOMER_TYPE
FROM CUSTOMERS C JOIN
ORDERS O ON 
C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID; -- CASE OF CASE IS LIKE IF( IF-ELSE) ELSE

-- 17. Segment customers by spending.
SELECT C.CUSTOMER_NAME,SUM(O.AMOUNT) AMOUNT_SPEND,
CASE 
	WHEN SUM(O.AMOUNT)> 50000 THEN 'HIGH'
    WHEN SUM(O.AMOUNT) BETWEEN 30000 AND 50000 THEN 'MEDIUM'
    ELSE 'LOW'
END AS SPEND_VAL
FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME;

-- 18. City-wise revenue using CASE.
SELECT C.CITY,SUM(O.AMOUNT) AS CITY_WISE_SPEND,
CASE 
	WHEN SUM(O.AMOUNT)>150000 THEN 'HIGH'
    WHEN SUM(O.AMOUNT) BETWEEN 130000 AND 150000 THEN 'AVERAGE'
    ELSE 'LOW'
END AS CITY_SPEND_RANGE
FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY
ORDER BY
CASE 
	WHEN SUM(O.AMOUNT)>150000 THEN 1
    WHEN SUM(O.AMOUNT) BETWEEN 130000 AND 150000 THEN 2
    ELSE 3
END;

-- 19. Average for completed orders.
SELECT 
AVG(
	CASE UPPER(STATUS)
		WHEN 'COMPLETED' THEN AMOUNT
        ELSE 0
	END
) AS AVG_AMOUNT_FOR_COMPLETED_ORDER
FROM ORDERS;

-- LET'S CALCULATE CITY-WISE AVG ORDER FOR COMPLETED STATUS
SELECT C.CITY,
CEIL(AVG(
	CASE UPPER(O.STATUS)
		WHEN 'COMPLETED' THEN AMOUNT
        ELSE 0
	END
)) AS AVG_AMOUNT_FOR_COMPLETED_ORDER
FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY;
		
-- 20. CASE inside GROUP BY. -- > for using CASE inside group by, we need to use case to create a column, then we can use same case to group
-- let's say we have defined amount>50000 as 'high' and 20k to 30k as 'average' and others as 'low', and then we want to calculate total number of orders and sum(amount) under these
SELECT
CASE
	WHEN AMOUNT>20000 THEN 'HIGH'
    WHEN AMOUNT BETWEEN 10000 AND 20000 THEN 'AVERAGE'
    ELSE 'LOW'
END AS SPEND_CATEGORY,
COUNT(*) AS TOTAL_ORDERS, SUM(AMOUNT) AS AMOUNT_PER_SPEND_CATEGORY
FROM ORDERS
GROUP BY
CASE
	WHEN AMOUNT>20000 THEN 'HIGH'
    WHEN AMOUNT BETWEEN 10000 AND 20000 THEN 'AVERAGE'
    ELSE 'LOW'
END;

-- 21. Categorize delivery delay.
SELECT ORDER_DATE,DELIVERY_DATE,
CASE
	WHEN DATEDIFF(DELIVERY_DATE,ORDER_DATE)>=7 THEN 'HIGH'
    WHEN DATEDIFF(DELIVERY_DATE,ORDER_DATE) BETWEEN 3 AND 6 THEN 'MEDIUM'
    ELSE 'LOW'
END AS DELIVERY_DELAY
FROM ORDERS;

-- 22. Classify by order frequency. - group customers based on number of orders per customer
SELECT CUSTOMER_ID,
CASE
	WHEN COUNT(ORDER_ID)> 10 THEN 'HIGH'
    WHEN COUNT(ORDER_ID) BETWEEN 5 AND 10 THEN 'AVERAGE'
    ELSE 'LOW'
END AS ORDER_FREQUENCY
FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY
CASE
	WHEN COUNT(ORDER_ID)> 10 THEN 1
    WHEN COUNT(ORDER_ID) BETWEEN 5 AND 10 THEN 2
    ELSE 3
END;
-- 23. Mark Active vs Inactive.
SELECT C.CUSTOMER_ID,O.ORDER_ID,
CASE 
	WHEN O.ORDER_ID IS NULL THEN 'INACTIVE'
    ELSE 'ACTIVE'
END AS CUSTOMER_ACTIVITY
FROM CUSTOMERS C LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 24. Categorize age bands.
SELECT CUSTOMER_NAME,
CASE
	WHEN YEAR(current_date())-YEAR(SIGNUP_DATE) >=60 THEN 'SENIOR CITIZEN'
    WHEN YEAR(current_date())-YEAR(SIGNUP_DATE) BETWEEN 18 AND 59 THEN 'ADULT'
    ELSE 'BELOW 18'
END AS AGE_BAND
FROM CUSTOMERS;

-- 25. Categorize revenue buckets.
SELECT YEAR(ORDER_DATE),SUM(AMOUNT) AS YEARLY_REVENUE,
CASE 
	WHEN SUM(AMOUNT)> 500000 THEN 'HIGH'
    ELSE 'LOW'
END AS REV_BAND
FROM ORDERS
GROUP BY YEAR(ORDER_DATE);

-- 26. Nested CASE membership + city.
SELECT CUSTOMER_NAME,
CASE UPPER(MEMBERSHIP_TYPE)
	WHEN 'GOLD' THEN
		CASE CITY
			WHEN 'Delhi' Then 'YES'
            ELSE 'NO'
		END
	END AS DELHI_GOLD_MEMBER
FROM CUSTOMERS;

-- 27. CASE inside MAX.
SELECT YEAR(ORDER_DATE),
MAX(
	CASE STATUS
		WHEN 'Completed' THEN AMOUNT
        ELSE 0
	END
) AS MAX_YEARLY_COMPLETED_ORDER_VAL
FROM ORDERS
GROUP BY YEAR(ORDER_DATE);

-- 28. CASE inside MIN.
SELECT YEAR(ORDER_DATE),
MIN(
	CASE STATUS
		WHEN 'Completed' THEN AMOUNT
        ELSE 0
	END
) AS MIN_YEARLY_COMPLETED_ORDER_VAL
FROM ORDERS
GROUP BY YEAR(ORDER_DATE);

-- 29. Yearly revenue buckets.
SELECT YEAR(ORDER_DATE),SUM(AMOUNT) AS YEARLY_REVENUE,
CASE 
	WHEN SUM(AMOUNT)> 500000 THEN 'HIGH'
    ELSE 'LOW'
END AS REV_BAND
FROM ORDERS
GROUP BY YEAR(ORDER_DATE);

-- 30. Customer classification using activity + spending.
SELECT 
    customer_id,
    SUM(amount) AS total_spent,
    MAX(order_date) AS last_order_date,

    CASE 
        WHEN MAX(order_date) >= CURRENT_DATE - INTERVAL 30 DAY 
             AND SUM(amount) >= 50000 
        THEN 'Active High Value'

        WHEN MAX(order_date) >= CURRENT_DATE - INTERVAL 30 DAY 
             AND SUM(amount) < 50000 
        THEN 'Active Low Value'

        WHEN MAX(order_date) < CURRENT_DATE - INTERVAL 30 DAY 
             AND SUM(amount) >= 50000 
        THEN 'Inactive High Value'

        ELSE 'Inactive Low Value'
    END AS customer_category

FROM orders
GROUP BY customer_id;