USE DAY5;

-- GET ALL THE TABLE COLUMNS IN 1 PLACE
SELECT UPPER(TABLE_NAME),GROUP_CONCAT(UPPER(COLUMN_NAME) ORDER BY ORDINAL_POSITION SEPARATOR ' ,') AS COLS FROM
INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='DAY5'
GROUP BY TABLE_NAME;


-- 	CUSTOMERS	CUSTOMER_ID ,CUSTOMER_NAME ,CITY ,AGE
-- 	DEPARTMENTS	DEPT_ID ,DEPT_NAME ,LOCATION
-- 	EMPLOYEES	EMP_ID ,NAME ,DEPT_ID ,SALARY ,HIRE_DATE ,AGE
-- 	ORDERS	ORDER_ID ,CUSTOMER_ID ,ORDER_DATE
-- 	PRODUCTS	PRODUCT_ID ,PRODUCT_NAME ,PRICE
-- 	TRANSACTIONS	TXN_ID ,ORDER_ID ,PRODUCT_ID ,QUANTITY ,AMOUNT

-- Q1. Retrieve all employees whose salary is greater than the overall average salary (use scalar subquery).
SELECT * FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES);

-- Q2. Find employees who belong to departments that have more than 5 employees (use multi-row subquery with IN).
SELECT * FROM EMPLOYEES WHERE DEPT_ID IN (
	SELECT DEPT_ID FROM EMPLOYEES GROUP BY DEPT_ID HAVING COUNT(*)>5)
    ORDER BY DEPT_ID;
    
-- Q3. Get all employees whose salary is equal to the maximum salary in the company (use scalar subquery).
SELECT * FROM EMPLOYEES WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);

-- Q4. Retrieve employees who earn more than the average salary of their own department (use correlated subquery).
SELECT E1.* FROM EMPLOYEES E1 WHERE SALARY>(
	SELECT AVG(SALARY) FROM EMPLOYEES E2 WHERE E1.DEPT_ID=E2.DEPT_ID GROUP BY DEPT_ID ) ORDER BY E1.DEPT_ID;

-- JUST TO CHECK WE CAN SEE WHAT IS THE AVG SALARY OF DEPT_ID=1, WHO ALL HAVE SALARY>AVG SALARY OF DEPT1
SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPT_ID=1; -- 36666.6667; 
SELECT * FROM EMPLOYEES WHERE DEPT_ID=1; -- > ONLY AMIT'S SALARY IS GREATER THAN AVG(SALARY) OF DEPT_ID, SO WE ARE GETTING CORRECT RESULT

-- Q5. Find departments where the average salary is greater than 60,000 (use subquery with GROUP BY).
SELECT * FROM DEPARTMENTS WHERE DEPT_ID IN
(
SELECT DEPT_ID FROM
(
	SELECT DEPT_ID,AVG(SALARY) FROM EMPLOYEES GROUP BY DEPT_ID HAVING AVG(SALARY)>60000
) X
);

-- Q6. Get employees who are not assigned to any department present in the departments table (use NOT IN with subquery).
SELECT * FROM EMPLOYEES WHERE DEPT_ID NOT IN (SELECT DISTINCT(DEPT_ID) FROM DEPARTMENTS);

-- Q7. Retrieve employees who have the same salary as at least one other employee (use correlated subquery).
SELECT E1.* FROM EMPLOYEES E1 WHERE E1.SALARY IN (SELECT SALARY FROM EMPLOYEES E2 WHERE E1.EMP_ID <> E2.EMP_ID) ORDER BY E1.SALARY;

-- Q8. Find employees whose salary is greater than ALL salaries in department 'HR' (use ALL operator).
SELECT * FROM EMPLOYEES WHERE SALARY > ALL 
(SELECT E.SALARY FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID WHERE D.DEPT_NAME='HR');

-- BEST WAY IS TO FIND MAX SALARY OF DEPT HR, AND CHECK WHICH ALL EMPLOYEES HAVE SALARY GREATER THAN IT

-- Q9. Retrieve employees whose salary is less than ANY salary in department 'Finance' (use ANY operator).
SELECT * FROM EMPLOYEES WHERE SALARY < ALL 
(SELECT E.SALARY FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID WHERE UPPER(D.DEPT_NAME)='FINANCE');

-- Q10. Find the second highest salary using subquery.
-- WAY1- BUT IT WILL GIVE 2ND ROW WITH ORDERED BY SALARY, BUT SALARY CAN BE SAME
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 1 OFFSET 1;

-- WAY2 - NEED TO USE SUBQUERY WITH LIMIT
SELECT * FROM EMPLOYEES WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEES) ORDER BY SALARY DESC LIMIT 1; -- LIMIT TO 1 ROW TO GET THE TOP AMONG SECOND HIGH

-- WAY3 - IT WILL GIVE ALL THE ROWS THAT HAVE SECOND HIGHEST SALARY
SELECT * FROM EMPLOYEES WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEES));

-- WAY4 -USE ROW_NUMBER() BELOW QUERY WILL GIVE 
SELECT MAX_SAL FROM (
SELECT MAX(SALARY) AS MAX_SAL,ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS RN FROM EMPLOYEES GROUP BY SALARY
) X WHERE X.RN=2;

-- Q11. Get employees who have salary greater than department-wise average and also belong to departments with more than 3 employees (combine correlated + multi-row subquery).
SELECT E1.* FROM EMPLOYEES E1
WHERE E1.SALARY>(SELECT AVG(E2.SALARY) FROM EMPLOYEES E2 WHERE E1.DEPT_ID=E2.DEPT_ID) AND
E1.DEPT_ID IN
(
	SELECT DEPT_ID FROM EMPLOYEES GROUP BY DEPT_ID HAVING COUNT(*)>3
) ORDER BY E1.SALARY,E1.DEPT_ID;

-- Q12. Retrieve departments that have at least one employee earning more than 100,000 (use EXISTS).
SELECT DISTINCT(DEPT_ID) FROM EMPLOYEES E1 WHERE EXISTS (SELECT 1 FROM EMPLOYEES E2 WHERE E2.SALARY>100000 AND E1.DEPT_ID=E2.DEPT_ID);

-- Q13. Find employees whose salary is less than the average salary of all employees except themselves (correlated subquery edge case).
SELECT E1.* FROM EMPLOYEES E1 WHERE E1.SALARY<(SELECT AVG(E2.SALARY) FROM EMPLOYEES E2 WHERE E1.EMP_ID<>E2.EMP_ID);

-- Q14. Use a CTE to calculate total salary per department and display department-wise totals.
WITH DEPT_CTE AS
(
	SELECT D.DEPT_NAME,SUM(E.SALARY) AS DEPT_WISE_TOTAL FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME ORDER BY SUM(E.SALARY)
)
SELECT * FROM DEPT_CTE;

-- Q15. Use a CTE to find the average salary of each department and list employees along with their department average.
WITH DEPT_CTE AS
(
	SELECT D.DEPT_NAME,AVG(E.SALARY) AS DEPT_WISE_AVG FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME ORDER BY AVG(E.SALARY)
)
SELECT E1.*,D1.DEPT_NAME,D2.DEPT_WISE_AVG FROM 
EMPLOYEES E1 JOIN DEPARTMENTS D1 ON E1.DEPT_ID=D1.DEPT_ID
JOIN DEPT_CTE D2 ON D1.DEPT_NAME=D2.DEPT_NAME;

-- Q16. Using a CTE, retrieve employees whose salary is above their department average (Deliverable requirement).
WITH DEPT_CTE AS
(
	SELECT D.DEPT_NAME,AVG(E.SALARY) AS DEPT_WISE_AVG FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME ORDER BY AVG(E.SALARY)
)
SELECT E1.*,D1.DEPT_NAME,D2.DEPT_WISE_AVG FROM 
EMPLOYEES E1 JOIN DEPARTMENTS D1 ON E1.DEPT_ID=D1.DEPT_ID
JOIN DEPT_CTE D2 ON D1.DEPT_NAME=D2.DEPT_NAME
WHERE E1.SALARY>D2.DEPT_WISE_AVG;

-- Q17. Create a CTE to calculate total revenue per department and then find the department with the highest revenue (Deliverable requirement).
WITH DEPT_CTE AS
(
	SELECT D.DEPT_NAME,SUM(E.SALARY) AS DEPT_WISE_TOTAL FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME ORDER BY SUM(E.SALARY) DESC
)
SELECT DEPT_NAME,DEPT_WISE_TOTAL FROM DEPT_CTE
WHERE DEPT_WISE_TOTAL = (SELECT MAX(DEPT_WISE_TOTAL) FROM DEPT_CTE);

-- Q18. Use multiple CTEs to first calculate department employee count and then filter departments with more than 10 employees.
WITH DEPT_EMP_CTE AS
(
	SELECT D.DEPT_NAME,COUNT(E.EMP_ID) AS DEPT_WISE_EMP_CNT FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME ORDER BY COUNT(E.EMP_ID) DESC
),
DEPT_EMP_CNT_MORE_THAN_10 AS
(
	SELECT DEPT_NAME, DEPT_WISE_EMP_CNT FROM DEPT_EMP_CTE WHERE DEPT_WISE_EMP_CNT>10
)
SELECT * FROM DEPT_EMP_CNT_MORE_THAN_10;

-- Q19. Use CTE chaining to calculate total and average salary per department in separate CTEs and join them.
WITH DEPT_CTE1 AS
(
	SELECT D.DEPT_NAME,SUM(E.EMP_ID) AS DEPT_WISE_TOT_SAL FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME
), DEPT_CTE2 AS
(
	SELECT D.DEPT_NAME,AVG(E.EMP_ID) AS DEPT_WISE_AVG_SAL FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME
)
SELECT D1.DEPT_NAME, D1.DEPT_WISE_TOT_SAL,D2.DEPT_WISE_AVG_SAL FROM DEPT_CTE1 D1 JOIN DEPT_CTE2 D2
ON D1.DEPT_NAME=D2.DEPT_NAME;

-- Q20. Use a CTE with JOIN to combine employee and department tables and show employee name, department name, and salary.
WITH CTE1 AS
(
	SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME,E.SALARY FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID
)
SELECT * FROM CTE1;

-- Q21. Create a CTE to rank employees by salary within each department and retrieve top 3 earners per department.
WITH DEPT_SAL_RANK AS
(
	SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME,E.SALARY,ROW_NUMBER() OVER(PARTITION BY D.DEPT_NAME ORDER BY E.SALARY DESC) AS RNK
    FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID
)
SELECT * FROM DEPT_SAL_RANK WHERE RNK<4;

-- Q22. Use a CTE to calculate cumulative salary expense by department over time (running total).
WITH CUME_CTE AS
(
	SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME,E.HIRE_DATE,E.SALARY, SUM(E.SALARY) OVER(PARTITION BY D.DEPT_NAME ORDER BY E.HIRE_DATE) AS CUMM_SUM
    FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID
)
SELECT * FROM CUME_CTE;

-- Q23. Use a CTE to identify duplicate employee records based on same name and department. LET'S SAY DUPS ARE ON SAME NAME,AGE,DEPT,SAL,HIRE
WITH DUP_CTE AS
(
	SELECT *,ROW_NUMBER() OVER(PARTITION BY NAME,DEPT_ID,SALARY,AGE,HIRE_DATE) AS RN FROM EMPLOYEES
) SELECT * FROM DUP_CTE WHERE RN>1;


-- Q24. Create a CTE to filter employees hired in the last 2 years and then calculate their average salary.
WITH EMP_HIRED_LAST2_YEAR AS
(
	SELECT * FROM EMPLOYEES WHERE DATEDIFF(CURRENT_DATE,HIRE_DATE)<2*365
)
SELECT AVG(SALARY) FROM EMP_HIRED_LAST2_YEAR;


-- Q25. Use nested CTEs to first filter high-paying departments and then list employees in those departments.
WITH HIGH_PAYING_DEPT AS
(
	SELECT D.DEPT_NAME FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID 
    GROUP BY D.DEPT_NAME ORDER BY AVG(SALARY) DESC LIMIT 3
),
LIST_OF_EMP_IN_HIGH_PAYING_DEPT AS
(
	SELECT E.EMP_ID,E.NAME,E.SALARY,D.DEPT_NAME FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID
    WHERE D.DEPT_NAME IN (SELECT * FROM HIGH_PAYING_DEPT)
)
SELECT * FROM LIST_OF_EMP_IN_HIGH_PAYING_DEPT;

-- Q26. Use a CTE to calculate department-wise revenue and then join with employees to show contribution.
WITH DEPTWISE_TOTAL_SALARY_CTE AS
(
	SELECT D.DEPT_NAME, SUM(E.SALARY)AS DEPT_SAL_TOTAL
    FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME
), EMP_CONTRI_CTE AS
(
	SELECT E.EMP_ID,E.NAME,D.DEPT_NAME,E.SALARY,(E.SALARY/D2.DEPT_SAL_TOTAL)*100 AS PER_EMP_CONTRI_IN_DEPT
    FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID
    JOIN DEPTWISE_TOTAL_SALARY_CTE D2 ON D.DEPT_NAME=D2.DEPT_NAME
)
SELECT * FROM EMP_CONTRI_CTE ORDER BY PER_EMP_CONTRI_IN_DEPT DESC;

-- Q27. Use correlated subquery to find employees who earn the highest salary in their respective departments.
SELECT E1.* FROM EMPLOYEES E1 WHERE E1.SALARY=(SELECT MAX(E2.SALARY) FROM EMPLOYEES E2 WHERE E1.DEPT_ID=E2.DEPT_ID);

-- Q28. Use a CTE with aggregation and HAVING clause to find departments with total salary greater than 500,000.
WITH AGG_CTE AS
(
	SELECT D.DEPT_NAME FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID
    GROUP BY D.DEPT_NAME HAVING SUM(E.SALARY)>500000
)
SELECT * FROM AGG_CTE;

-- Q29. Use a subquery inside SELECT clause to show each employee's salary along with company average salary.
SELECT EMP_ID,NAME,SALARY,(SELECT AVG(SALARY) FROM EMPLOYEES) AS COMPANY_AVG_SALARY FROM EMPLOYEES;

-- Q30. Combine CTE and subquery: create a CTE for department averages and then use a subquery to filter employees above overall average but below department max.
WITH DEPT_AVG_CTE AS
(
	SELECT D.DEPT_NAME,AVG(E.SALARY) AS DEPT_WISE_AVG FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPT_ID=D.DEPT_ID GROUP BY D.DEPT_NAME ORDER BY AVG(E.SALARY)
)
SELECT E1.*,D.DEPT_NAME FROM EMPLOYEES E1
JOIN DEPARTMENTS D ON E1.DEPT_ID=D.DEPT_ID
WHERE E1.SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES)
AND E1.SALARY<(SELECT D1.DEPT_WISE_AVG FROM DEPT_AVG_CTE D1 WHERE D.DEPT_NAME=D1.DEPT_NAME);
