USE DAY2;
SHOW COLUMNS FROM CUSTOMERS;  -- Give the name of all the columns in a table
-- Get all the columns in a row
SELECT GROUP_CONCAT(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='customers' and TABLE_SCHEMA='DAY2';
-- RES: city,customer_id,customer_name,dob,membership_type,signup_date

SELECT GROUP_CONCAT(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='orders' and TABLE_SCHEMA='DAY2';
-- RES: amount,customer_id,delivery_date,order_date,order_id,payment_mode,status

-- DATE FUNCTION QUESTIONS
-- 1. Show all customers with their signup year.
SELECT CUSTOMER_NAME, YEAR(SIGNUP_DATE) AS SIGNUP_YEAR FROM CUSTOMERS;
SELECT CUSTOMER_NAME,EXTRACT(YEAR FROM SIGNUP_DATE) AS SIGNUP_YEAR FROM CUSTOMERS;

-- 2. Display month of each order_date.
SELECT MONTH(ORDER_DATE) AS ORDER_MONTH ,ORDER_ID FROM ORDERS;
SELECT MONTHNAME(ORDER_DATE) AS MONTH_NAME,ORDER_ID FROM ORDERS;
SELECT EXTRACT(MONTH FROM ORDER_DATE) AS ORDER_MONTH, ORDER_ID FROM ORDERS;

-- 3. Show current date along with customer names.
SELECT CURRENT_DATE(), CUSTOMER_NAME FROM CUSTOMERS;

-- 4. Extract day from order_date.
SELECT DAYNAME(ORDER_DATE) AS DAY_OF_ORDER, ORDER_ID FROM ORDERS;

-- 5. Show current timestamp for each order.
SELECT CURRENT_TIMESTAMP(), ORDER_ID FROM ORDERS;

-- 6. Find customers who joined in current year.
SELECT CUSTOMER_NAME,SIGNUP_DATE FROM CUSTOMERS WHERE YEAR(SIGNUP_DATE)=YEAR(CURRENT_DATE());

-- 7. Show orders placed in the current month.
SELECT ORDER_ID,ORDER_DATE FROM ORDERS WHERE MONTH(ORDER_DATE)=MONTH(CURRENT_DATE());

-- 8. Find orders placed in the previous month.
SELECT * FROM ORDERS WHERE MONTH(ORDER_DATE)=MONTH(CURRENT_DATE())-1;

-- 9. Show customers whose birthday month = current month.
SELECT CUSTOMER_NAME, DOB FROM CUSTOMERS WHERE MONTH(DOB)=MONTH(CURRENT_DATE());

-- 10. Add 30 days to signup_date.
SELECT SIGNUP_DATE, DATE_ADD(SIGNUP_DATE,INTERVAL 30 DAY) AS 30_DAYS_PLUS_MONTH FROM CUSTOMERS;

-- 11. Find difference between delivery_date and order_date.
SELECT ORDER_ID,DATEDIFF(DELIVERY_DATE,ORDER_DATE) AS DAYS_TOOK_TO_DELIVER FROM ORDERS;

-- 12. Show customers who joined in last 90 days.- Since we have no order in 2026, let's take last signup date is 2025-01-27, so let's take the date as Jan 2025 last
SELECT CUSTOMER_NAME,SIGNUP_DATE FROM CUSTOMERS WHERE DATEDIFF('2025-01-31', SIGNUP_DATE)<90;

-- 13. Extract quarter from order_date.
SELECT QUARTER(ORDER_DATE), ORDER_DATE FROM ORDERS;

-- 14. Find orders older than 15 days. -- > We will take reference of 2025-01-31 as current date, else we can use CURRENT_DATE() function
SELECT ORDER_ID, ORDER_DATE FROM ORDERS WHERE DATEDIFF('2025-01-31',ORDER_DATE)>15;

-- 15. Show month-wise count of orders. ---FOR THE PURPOSE OF THIS QUESTION LET'S TAKE YEAR TO BE 2024
SELECT COUNT(ORDER_ID), MONTHNAME(ORDER_DATE) AS MONTH_NAME FROM ORDERS WHERE YEAR(ORDER_DATE)='2024'
GROUP BY MONTHNAME(ORDER_DATE) ORDER BY COUNT(ORDER_ID) DESC;

SELECT COUNT(ORDER_ID), MONTHNAME(ORDER_DATE) AS MONTH_NAME, YEAR(ORDER_DATE) FROM ORDERS
GROUP BY YEAR(ORDER_DATE),MONTHNAME(ORDER_DATE) ORDER BY YEAR(ORDER_DATE),MONTHNAME(ORDER_DATE),COUNT(ORDER_ID) DESC; -- Gives Year wise month total order count

-- 16. Find customer with earliest signup_date.
SELECT * FROM CUSTOMERS ORDER BY SIGNUP_DATE DESC LIMIT 1;

-- 17. Show latest order per customer.
-- For this we need last order date of each customer and then we can join it with orders to get the whole detail
SELECT O1.* FROM ORDERS O1 JOIN
(
SELECT CUSTOMER_ID,MAX(ORDER_DATE) AS MAX_DATE FROM ORDERS GROUP BY CUSTOMER_ID
) O2 ON
O1.CUSTOMER_ID=O2.CUSTOMER_ID AND
O1.ORDER_DATE=O2.MAX_DATE;

-- To check this we can check the arrange all the orders for any customer
SELECT * FROM ORDERS WHERE CUSTOMER_ID=1 ORDER BY ORDER_DATE DESC;

-- 18. Find customers who ordered in same month as signup.
SELECT C.CUSTOMER_NAME,C.CUSTOMER_ID,C.SIGNUP_DATE,O.ORDER_ID,O.ORDER_DATE FROM CUSTOMERS C 
JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE
MONTH(C.SIGNUP_DATE)=MONTH(O.ORDER_DATE);

-- 19. Show year-wise revenue.
SELECT SUM(AMOUNT) AS YEARLY_REVENUE, YEAR(ORDER_DATE) AS WHICH_YEAR FROM ORDERS
GROUP BY YEAR(ORDER_DATE) ORDER BY YEAR(ORDER_DATE);

-- 20. Find average delivery delay per month.
SELECT CEIL(AVG(DATEDIFF(DELIVERY_DATE,ORDER_DATE))) AS AVG_DELIVERY_DELAY, MONTHNAME(ORDER_DATE),YEAR(ORDER_DATE) FROM ORDERS
GROUP BY YEAR(ORDER_DATE),MONTHNAME(ORDER_DATE) ORDER BY YEAR(ORDER_DATE),MONTHNAME(ORDER_DATE);  
-- >important- GROUP BY SHOULD HAVE ALL THE NON-AGGREGATE COLUMNS UNDER GROUP BY

-- 21. Show customers inactive for last 180 days. 
SELECT C.CUSTOMER_NAME, DATEDIFF(O.ORDER_DATE,C.SIGNUP_DATE) AS INACTIVE_NO_DAYS
FROM CUSTOMERS C JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE DATEDIFF(O.ORDER_DATE,C.SIGNUP_DATE)>180;

-- 22. Find first order date city-wise.
SELECT MIN(ORDER_DATE),C.CITY FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY;

-- 23. Show month having maximum orders.
SELECT T1.ORDER_COUNT,T1.ORDER_MONTH,T1.ORDER_YEAR FROM
(
SELECT COUNT(ORDER_ID) AS ORDER_COUNT,MONTH(ORDER_DATE) AS ORDER_MONTH,YEAR(ORDER_DATE) AS ORDER_YEAR FROM ORDERS
GROUP BY YEAR(ORDER_DATE),MONTH(ORDER_DATE)
) T1
WHERE T1.ORDER_COUNT =
(
	SELECT MAX(T2.ORDER_COUNT) FROM
    (
		SELECT COUNT(ORDER_ID) AS ORDER_COUNT,MONTH(ORDER_DATE) AS ORDER_MONTH,YEAR(ORDER_DATE) AS ORDER_YEAR FROM ORDERS
		GROUP BY YEAR(ORDER_DATE),MONTH(ORDER_DATE)
	) AS T2
    WHERE  T1.ORDER_YEAR=T2.ORDER_YEAR
) ORDER BY T1.ORDER_YEAR,T1.ORDER_MONTH;

-- same query with join
SELECT T1.ORDER_COUNT,T1.ORDER_MONTH,T1.ORDER_YEAR FROM
(
SELECT COUNT(ORDER_ID) AS ORDER_COUNT,MONTH(ORDER_DATE) AS ORDER_MONTH,YEAR(ORDER_DATE) AS ORDER_YEAR FROM ORDERS
GROUP BY YEAR(ORDER_DATE),MONTH(ORDER_DATE)
) T1 JOIN
(
	SELECT MAX(ORDER_COUNT) AS MAX_ORDER_VAL,ORDER_YEAR FROM
    (
		SELECT COUNT(ORDER_ID) AS ORDER_COUNT,MONTH(ORDER_DATE) AS ORDER_MONTH,YEAR(ORDER_DATE) AS ORDER_YEAR FROM ORDERS
		GROUP BY YEAR(ORDER_DATE),MONTH(ORDER_DATE)
	) X
    GROUP BY ORDER_YEAR
) T2
    WHERE  T1.ORDER_YEAR=T2.ORDER_YEAR AND
    T1.ORDER_COUNT=T2.MAX_ORDER_VAL
    ORDER BY T1.ORDER_YEAR,T1.ORDER_MONTH;


-- 24. Find orders delivered after 7 days.
SELECT ORDER_ID, ORDER_DATE,DELIVERY_DATE FROM ORDERS WHERE DATEDIFF(DELIVERY_DATE,ORDER_DATE)>7;

-- 25. Show yearly customer acquisition trend.
SELECT COUNT(CUSTOMER_ID),YEAR(SIGNUP_DATE) AS YEAR_NAME FROM CUSTOMERS 
GROUP BY YEAR(SIGNUP_DATE) ORDER BY YEAR(SIGNUP_DATE);

-- 26. Find customers whose signup anniversary is today.
SELECT * FROM CUSTOMERS WHERE MONTH(SIGNUP_DATE)=MONTH(CURRENT_DATE()) AND DAY(SIGNUP_DATE)=DAY(CURRENT_DATE());
SELECT *,DATE_FORMAT(SIGNUP_DATE,'%m-%d') AS MON_DATE FROM CUSTOMERS; -- > Can be used to extract date in some format

-- 27. Compare signup month vs order month.
SELECT MONTH(C.SIGNUP_DATE) AS SIGNUP_MONTH,MONTH(O.ORDER_DATE) AS ORDER_MONTH FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID=O.ORDER_ID;

-- 28. Find oldest customer using dob.
SELECT * FROM CUSTOMERS WHERE DOB=(SELECT MIN(DOB) FROM CUSTOMERS);

-- 29. Show orders placed on weekends.
SELECT *, DAYNAME(ORDER_DATE) AS DAY_NAME FROM ORDERS WHERE UPPER(DAYNAME(ORDER_DATE)) IN ('SUNDAY','SATURDAY');

-- 30. Find monthly revenue growth.
SELECT SUM(AMOUNT) AS MONTHLY_REVENUE,YEAR(ORDER_DATE),MONTHNAME(ORDER_DATE) AS MONTH_NAME FROM ORDERS
GROUP BY YEAR(ORDER_DATE),MONTHNAME(ORDER_DATE) ORDER BY YEAR(ORDER_DATE),MONTHNAME(ORDER_DATE);