USE CUSTOMER_DATABASE;

-- Q1: Count customers city-wise.
SELECT COUNT(CUSTOMER_NAME) AS TOTAL_CUSTOMERS_PER_CITY,CITY FROM CUSTOMERS GROUP BY CITY ORDER BY COUNT(CUSTOMER_NAME) DESC;

-- Q2: Average age city-wise.
SELECT ROUND(AVG(AGE)) AS AVG_AGE_PER_CITY,CITY FROM CUSTOMERS GROUP BY CITY;

-- Q3: Count orders customer-wise.
SELECT COUNT(ORDER_ID) AS TOTAL_ORDER_PER_CUSTOMER,CUSTOMER_ID FROM ORDERS GROUP BY CUSTOMER_ID ORDER BY CUSTOMER_ID;

-- Q4: Sum orders customer-wise. -- WILL BE THE SAME QUERY AS Q3 AS SUM WILL ALSO RESULT IN COUNT OF ORDERS

-- Q5: Count products product-wise.
SELECT COUNT(PRODUCT_NAME) AS COUNT_OF_PER_PRODUCT_ORDER, PRODUCT_NAME FROM ORDERS GROUP BY PRODUCT_NAME;
SELECT COUNT(*) FROM ORDERS WHERE PRODUCT_NAME='Laptop'; -- >Just to validate above result

-- Q6: Sum revenue product-wise.
SELECT SUM(AMOUNT) AS TOT_REV_PER_PRODUCT, PRODUCT_NAME FROM ORDERS GROUP BY PRODUCT_NAME;

-- Q7: Average amount product-wise.
SELECT AVG(AMOUNT) AS AVG_AMT_PER_PRODUCT, PRODUCT_NAME FROM ORDERS GROUP BY PRODUCT_NAME; -- NOTICE THERE IS ONE ZERO LESS THAN SUM
SELECT SUM(AMOUNT) FROM ORDERS WHERE PRODUCT_NAME='Laptop'; -- > JUST TO VALIDATE IF WE ARE GETTING CORRECT RESULT

-- Q8: Maximum order city-wise.
SELECT MAX(O.AMOUNT),C.CITY FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY; -- Need to use inner join to use city from customers table

-- Q9: Minimum order city-wise.
SELECT MIN(O.AMOUNT) AS MIN_AMOUNT_ORDER_PER_CITY,C.CITY FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY;

-- Q10: Count signup by month.
SELECT COUNT(CUSTOMER_ID),MONTHNAME(SIGNUP_DATE) AS MONTH FROM CUSTOMERS GROUP BY MONTHNAME(SIGNUP_DATE); -- Monthname() gives the month name from date as 'yyyy-mm-dd'

-- Q11: Count orders by month.
SELECT COUNT(ORDER_ID) AS TOTAL_ORDER_PER_MONTH, MONTHNAME(ORDER_DATE) AS MONTH FROM ORDERS GROUP BY MONTHNAME(ORDER_DATE);

-- Q12: Revenue month-wise.
SELECT SUM(AMOUNT) AS TOTAL_REVENUE_PER_MONTH, MONTHNAME(ORDER_DATE) AS MONTH FROM ORDERS GROUP BY MONTHNAME(ORDER_DATE);

-- Q13: Customers having more than 1 order.
SELECT COUNT(ORDER_ID) AS COUNT_OF_ORDERS_PER_CUSTOMER,CUSTOMER_ID FROM ORDERS
GROUP BY CUSTOMER_ID HAVING COUNT(ORDER_ID)>1 ORDER BY CUSTOMER_ID;

-- Q14: Products sold more than 5 times.
SELECT COUNT(ORDER_ID),PRODUCT_NAME FROM ORDERS 
GROUP BY PRODUCT_NAME HAVING COUNT(ORDER_ID)>5;

-- Q15: Customers whose total spending > 50000.
SELECT CUSTOMER_ID,SUM(AMOUNT) FROM ORDERS GROUP BY CUSTOMER_ID HAVING SUM(AMOUNT)>50000;

-- Q16: Cities having average age > 30.
SELECT CITY,AVG(AGE) FROM CUSTOMERS GROUP BY CITY HAVING AVG(AGE)>30;

-- Q17: Products with avg amount > 10000.
SELECT AVG(AMOUNT),PRODUCT_NAME FROM ORDERS GROUP BY PRODUCT_NAME HAVING AVG(AMOUNT)>10000;

-- Q18: Cities generating revenue > 20 lakh.
SELECT SUM(O.AMOUNT) AS REVENUE, C.CITY FROM CUSTOMERS C JOIN ORDERS O GROUP BY C.CITY HAVING SUM(O.AMOUNT)>2000000 ORDER BY SUM(O.AMOUNT);

-- Q19: Customers with spending above overall avg spending.
SELECT CUSTOMER_ID,SUM(AMOUNT) FROM ORDERS GROUP BY CUSTOMER_ID HAVING SUM(AMOUNT) > (SELECT AVG(AMOUNT) FROM ORDERS);

-- Q20: Top 3 grouped revenues.
SELECT SUM(AMOUNT), PRODUCT_NAME FROM ORDERS GROUP BY PRODUCT_NAME ORDER BY SUM(AMOUNT) DESC LIMIT 3;